'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { Search, Filter, Download, Eye } from 'lucide-react'
import { format } from 'date-fns'
import * as XLSX from 'xlsx'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { createClient } from '@/lib/supabase/client'
import { formatPKTShort, formatDatePKT, getCurrentPKT } from '@/lib/timezone'

interface Patient {
  id: string
  full_name: string
  gender: string
  age: number
  phone: string
  email: string | null
  address: string
  labels: string[]
  created_at: string
}

interface PatientTableProps {
  initialPatients: Patient[]
}

interface UserProfile {
  name: string
  clinic_name: string | null
  clinic_type: string | null
}

export function PatientTable({ initialPatients }: PatientTableProps) {
  const [patients, setPatients] = useState(initialPatients)
  const [searchTerm, setSearchTerm] = useState('')
  const [filterLabel, setFilterLabel] = useState<string>('all')
  const [userProfile, setUserProfile] = useState<UserProfile | null>(null)
  const supabase = createClient()

  // Fetch user profile on component mount
  useEffect(() => {
    async function fetchUserProfile() {
      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        const { data } = await supabase
          .from('profiles')
          .select('name, clinic_name, clinic_type')
          .eq('id', user.id)
          .single()
        
        if (data) {
          setUserProfile(data as UserProfile)
        }
      }
    }
    fetchUserProfile()
  }, [supabase])

  // Filter patients
  const filteredPatients = patients.filter(patient => {
    const matchesSearch = 
      patient.full_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      patient.phone.includes(searchTerm) ||
      (patient.email && patient.email.toLowerCase().includes(searchTerm.toLowerCase()))

    const matchesLabel = 
      filterLabel === 'all' || patient.labels.includes(filterLabel)

    return matchesSearch && matchesLabel
  })

  // Get unique labels
  const allLabels = Array.from(
    new Set(patients.flatMap(p => p.labels))
  )

  // Export to Excel
  const exportToExcel = () => {
    const nowPKT = getCurrentPKT()
    const timestamp = formatPKTShort(nowPKT)
    const clinicName = userProfile?.clinic_name || 'MyClinic Admin'
    const clinicType = userProfile?.clinic_type || 'Healthcare Facility'
    const printedBy = userProfile?.name || 'Administrator'

    // Create workbook
    const workbook = XLSX.utils.book_new()
    
    // Prepare data with header rows
    const headerData = [
      [clinicName],
      [clinicType],
      [''],
      ['Patient Records Report'],
      [`Generated: ${timestamp}`],
      [`Printed by: ${printedBy}`],
      [''],
      ['Full Name', 'Gender', 'Age', 'Phone', 'Email', 'Address', 'Labels', 'Registered'],
    ]
    
    const patientData = filteredPatients.map(p => [
      p.full_name,
      p.gender,
      p.age,
      p.phone,
      p.email || 'N/A',
      p.address,
      p.labels.join(', '),
      formatDatePKT(p.created_at),
    ])
    
    const footerData = [
      [''],
      ['This is a digitally printed record and doesn\'t require any verification or signature.'],
      ['In case of any issues please contact developer: Engr. Hammad Khurshid'],
      ['LinkedIn: https://www.linkedin.com/in/hammadkhurshid'],
      [''],
      ['Generated by MyClinic Admin - Made with ❤️ by Engr. Hammad Khurshid'],
      ['All times are in Pakistan Standard Time (PKT, UTC+5)'],
    ]
    
    const allData = [...headerData, ...patientData, ...footerData]
    
    const worksheet = XLSX.utils.aoa_to_sheet(allData)
    
    // Set column widths
    worksheet['!cols'] = [
      { wch: 20 }, // Full Name
      { wch: 10 }, // Gender
      { wch: 8 },  // Age
      { wch: 15 }, // Phone
      { wch: 25 }, // Email
      { wch: 30 }, // Address
      { wch: 20 }, // Labels
      { wch: 15 }, // Registered
    ]
    
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Patients')
    XLSX.writeFile(workbook, `patients_${format(nowPKT, 'yyyy-MM-dd_HHmm')}_PKT.xlsx`)
  }

  // Export to PDF
  const exportToPDF = () => {
    const doc = new jsPDF()
    const nowPKT = getCurrentPKT()
    const timestamp = formatPKTShort(nowPKT)
    const clinicName = userProfile?.clinic_name || 'MyClinic Admin'
    const clinicType = userProfile?.clinic_type || 'Healthcare Facility'
    const printedBy = userProfile?.name || 'Administrator'
    
    // Header Section
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text(clinicName, 14, 20)
    
    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text(clinicType, 14, 28)
    
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('Patient Records Report', 14, 40)
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Generated: ${timestamp}`, 14, 48)
    doc.text(`Printed by: ${printedBy}`, 14, 54)

    // Patient Data Table
    autoTable(doc, {
      startY: 62,
      head: [['Name', 'Gender', 'Age', 'Phone', 'Email']],
      body: filteredPatients.map(p => [
        p.full_name,
        p.gender,
        p.age.toString(),
        p.phone,
        p.email || 'N/A',
      ]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [0, 115, 230] },
    })

    // Footer Section
    const finalY = (doc as any).lastAutoTable.finalY || 62
    
    doc.setFontSize(9)
    doc.setFont('helvetica', 'italic')
    doc.text('This is a digitally printed record and doesn\'t require any verification or signature.', 14, finalY + 10)
    
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.text('In case of any issues please contact developer:', 14, finalY + 16)
    doc.text('Engr. Hammad Khurshid', 14, finalY + 21)
    
    doc.setTextColor(0, 0, 255)
    doc.textWithLink('LinkedIn Profile', 14, finalY + 26, { url: 'https://www.linkedin.com/in/hammadkhurshid' })
    
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'italic')
    doc.text('Generated by MyClinic Admin - Made with ❤️ by Engr. Hammad Khurshid', 14, finalY + 34)
    
    doc.setFontSize(8)
    doc.text('All times are in Pakistan Standard Time (PKT, UTC+5)', 14, finalY + 40)

    doc.save(`patients_${format(nowPKT, 'yyyy-MM-dd_HHmm')}_PKT.pdf`)
  }

  return (
    <div className="space-y-6">
      {/* Search and Filters */}
      <div className="flex flex-col md:flex-row gap-4">
        <div className="flex-1 relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search by name, phone, or email..."
            className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
          />
        </div>
        
        <div className="flex gap-2">
          <select
            value={filterLabel}
            onChange={(e) => setFilterLabel(e.target.value)}
            className="px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
          >
            <option value="all">All Labels</option>
            {allLabels.map(label => (
              <option key={label} value={label}>{label}</option>
            ))}
          </select>

          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={exportToExcel}
            className="flex items-center gap-2 px-4 py-3 bg-green-600 hover:bg-green-700 text-white rounded-lg font-medium transition"
          >
            <Download className="w-5 h-5" />
            <span className="hidden md:inline">Excel</span>
          </motion.button>

          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={exportToPDF}
            className="flex items-center gap-2 px-4 py-3 bg-red-600 hover:bg-red-700 text-white rounded-lg font-medium transition"
          >
            <Download className="w-5 h-5" />
            <span className="hidden md:inline">PDF</span>
          </motion.button>
        </div>
      </div>

      {/* Results Count */}
      <div className="text-sm text-gray-600">
        Showing {filteredPatients.length} of {patients.length} patients
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                  Patient
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                  Gender
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                  Age
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                  Contact
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                  Labels
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                  Registered
                </th>
                <th className="px-6 py-4 text-left text-sm font-semibold text-gray-900">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {filteredPatients.map((patient) => (
                <motion.tr
                  key={patient.id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="hover:bg-gray-50 transition"
                >
                  <td className="px-6 py-4">
                    <div className="font-medium text-gray-900">{patient.full_name}</div>
                  </td>
                  <td className="px-6 py-4 text-gray-600">{patient.gender}</td>
                  <td className="px-6 py-4 text-gray-600">{patient.age}</td>
                  <td className="px-6 py-4">
                    <div className="text-gray-900">{patient.phone}</div>
                    {patient.email && (
                      <div className="text-sm text-gray-600">{patient.email}</div>
                    )}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex flex-wrap gap-1">
                      {patient.labels.slice(0, 2).map(label => (
                        <span
                          key={label}
                          className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-primary-100 text-primary-800"
                        >
                          {label}
                        </span>
                      ))}
                      {patient.labels.length > 2 && (
                        <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                          +{patient.labels.length - 2}
                        </span>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-gray-600">
                    {format(new Date(patient.created_at), 'MMM d, yyyy')}
                  </td>
                  <td className="px-6 py-4">
                    <Link href={`/patients/${patient.id}`}>
                      <motion.button
                        whileHover={{ scale: 1.1 }}
                        whileTap={{ scale: 0.9 }}
                        className="p-2 text-primary-600 hover:bg-primary-50 rounded-lg transition"
                      >
                        <Eye className="w-5 h-5" />
                      </motion.button>
                    </Link>
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {filteredPatients.length === 0 && (
        <div className="text-center py-12 text-gray-500">
          No patients found matching your criteria
        </div>
      )}
    </div>
  )
}
